[project]
name = "my-uv-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "lakifase", email = "Pegor07@mail.ru" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
my-uv-app = "my_uv_app:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
